In [2]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.


In [3]:
# Yes, there is a difference in the data type of list_ and array_list. The list_ is a Python list object, whereas array_list is a NumPy ndarray object.

import numpy as np

list_ = ['1', '2', '3', '4', '5']

# Print the data type of the list variable
print(type(list_))

array_list = np.array(list_)

# Print the data type of the ndarray variable
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.


In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

# Print the data type of each element in the list
for element in list_:
    print(type(element))

# Print the data type of each element in the ndarray
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_, dtype=int)

# Print the data type of each element in the list
for element in list_:
    print(type(element))

# Print the data type of each element in the ndarray
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Yes, there will be a difference in the data type of the elements present in list_ and array_list after the change, because the dtype parameter in the np.array() function specifies the data type of the elements in the resulting NumPy ndarray.

In this case, the dtype parameter is set to int, which means that the elements in array_list will be of integer type.

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size



In [6]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# Print the shape of the ndarray
print("Shape of num_array:", num_array.shape)

# Print the size of the ndarray
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.


In [7]:
import numpy as np

zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?


In [8]:
import numpy as np

identity_matrix = np.identity(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
